version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: eco_mongo
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    container_name: eco_backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/ecoluz_db
      - JWT_SECRET=Ecoluz@2025!MeuSegredoJWT
      - PORT=5000
    depends_on:
      - mongodb

  frontend:
    build: ./frontend
    container_name: eco_frontend
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    depends_on:
      - backend

volumes:
  mongo_data:
